# Generated by Django 3.2.9 on 2021-12-01 12:17

from django.db import migrations, models
import src.blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=src.blog.models.upload_to, verbose_name='Image'),
        ),
    ]
